# This is used to manage Ansible role dependences
# http://docs.ansible.com/galaxy.html#installing-multiple-roles-from-a-file
# Install with: `ansible-galaxy install -r requirements.yml`

- src: geerlingguy.java
- src: geerlingguy.ruby
- src: geerlingguy.jenkins

