- name: Install Jenkins plugins.
  debug: var=jenkins_jar_location


- name: create pipeline-job
  command: java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/ create-job < /vagrant/job-config/config.xml
    creates=/var/lib/jenkins/jobs/pact_pipeline/config.xml
