

- yum: name=nss state=latest
- yum: name=java-1.8.0-openjdk-devel state=present

- script: git_init.sh
  args:
    creates: /vagrant/consumer-and-provider/.git

- template: src=hudson.tasks.Maven.xml dest=/var/lib/jenkins owner=jenkins group=jenkins mode=0755

- name: tell the host about our servers it might want to ssh to
  known_hosts: path='/etc/ssh/ssh_known_hosts'
               name='github.com'
               key="{{ lookup('file', 'pubkeys/github') }}"
- file: path=/etc/ssh/ssh_known_hosts mode=0755

- name: create pipeline-job
  shell: java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/ create-job {{ pact_job_name }} < /vagrant/job-config/config.xml
    creates=/var/lib/jenkins/jobs/{{ pact_job_name }}/config.xml

