
---

- hosts: all
  vars: 
    jenkins_connection_delay: 5
    jenkins_connection_retries: 60
    jenkins_hostname: localhost
    jenkins_http_port: 8080
    jenkins_jar_location: /opt/jenkins-cli.jar
    jenkins_url_prefix: ""
    pact_job_name: demo
  sudo: yes
  roles:
    - role: pact_job
  tags: pact_job
