
---
- hosts: all
  sudo: yes
  vars:
    java_packages:
      - java-1.8.0-openjdk-devel
    jenkins_plugins:
      - git
      - build-pipeline-plugin
      - pipeline-stage-view
      - pipeline-utility-steps
      - ssh
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
#    - role: geerlingguy.ruby
  tags: jenkins
  
- include: pact_job.yml